name: Deploy gh-pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install -g pnpm@7.30.5
          pnpm install
      - name: Build lib packages
        run: pnpm build
      - name: Build demo packages
        run: pnpm build:demo
      - name: Push to repository (to deploy gh-pagse)
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_FOR_PAGES }}
        run: |
          cd ./examples/dist
          git init
          git remote add origin https://github.com/CoderMonkie/vue-grabbing-box.git
          git config user.email maonianyou@foxmail.com
          # git pull origin gh-pages
          git add .
          git commit -m "auto deploy gh-pages for demo-vue2"
          git push -u origin master:gh-pages --force
