name: Publish NPM Package

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check version change
        run: |
          if [[ $(git diff HEAD~..HEAD -- package.json | grep version) ]]; then
            echo "Version changed, publishing to NPM..."
          else
            echo "Version not changed, skipping NPM publish."
            exit 1
          fi

      - name: Install dependencies
        if: ${{ success() }}
        run: |
          npm install -g pnpm@7.30.5
          pnpm install

      - name: Build package
        if: ${{ success() }}
        run: pnpm build

      - name: Append NPM token
        if: ${{ success() }}
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc

      - name: Publish package
        if: ${{ success() }}
        run: pnpm publish
